using System;
using System.IO;
using System.Xml;
using System.Xml.Serialization;

// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

// 
//This source code was auto-generated by MonoXSD
//
namespace Schemas {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class Studenci {
        
        private StudenciStudent studentField;
        
        /// <remarks/>
        public StudenciStudent Student {
            get {
                return this.studentField;
            }
            set {
                this.studentField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class StudenciStudent {
        
        private string imieField;
        
        private string nazwiskoField;
        
        private System.DateTime data_urField;
        
        private bool data_urSpecifiedField;
        
        private int rokField;
        
        private bool rokSpecifiedField;
        
        private StudenciStudentAdres_Staly adres_StalyField;
        
        private StudenciStudentAdres_Tymczasowy adres_TymczasowyField;
        
        private StudenciStudentPrzedmioty przedmiotyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string imie {
            get {
                return this.imieField;
            }
            set {
                this.imieField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string nazwisko {
            get {
                return this.nazwiskoField;
            }
            set {
                this.nazwiskoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime data_ur {
            get {
                return this.data_urField;
            }
            set {
                this.data_urField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnore()]
        public virtual bool data_urSpecified {
            get {
                return this.data_urSpecifiedField;
            }
            set {
                this.data_urSpecifiedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int rok {
            get {
                return this.rokField;
            }
            set {
                this.rokField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnore()]
        public virtual bool rokSpecified {
            get {
                return this.rokSpecifiedField;
            }
            set {
                this.rokSpecifiedField = value;
            }
        }
        
        /// <remarks/>
        public StudenciStudentAdres_Staly Adres_Staly {
            get {
                return this.adres_StalyField;
            }
            set {
                this.adres_StalyField = value;
            }
        }
        
        /// <remarks/>
        public StudenciStudentAdres_Tymczasowy Adres_Tymczasowy {
            get {
                return this.adres_TymczasowyField;
            }
            set {
                this.adres_TymczasowyField = value;
            }
        }
        
        /// <remarks/>
        public StudenciStudentPrzedmioty Przedmioty {
            get {
                return this.przedmiotyField;
            }
            set {
                this.przedmiotyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class StudenciStudentAdres_Staly {
        
        private string miejscowoscField;
        
        private string ulicaField;
        
        private string kodField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string miejscowosc {
            get {
                return this.miejscowoscField;
            }
            set {
                this.miejscowoscField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ulica {
            get {
                return this.ulicaField;
            }
            set {
                this.ulicaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string kod {
            get {
                return this.kodField;
            }
            set {
                this.kodField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class StudenciStudentAdres_Tymczasowy {
        
        private string miejscowoscField1;
        
        private string ulicaField1;
        
        private string kodField1;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string miejscowosc {
            get {
                return this.miejscowoscField1;
            }
            set {
                this.miejscowoscField1 = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ulica {
            get {
                return this.ulicaField1;
            }
            set {
                this.ulicaField1 = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string kod {
            get {
                return this.kodField1;
            }
            set {
                this.kodField1 = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class StudenciStudentPrzedmioty {
        
        private StudenciStudentPrzedmiotyPrzedmiot przedmiotField;
        
        /// <remarks/>
        public StudenciStudentPrzedmiotyPrzedmiot Przedmiot {
            get {
                return this.przedmiotField;
            }
            set {
                this.przedmiotField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class StudenciStudentPrzedmiotyPrzedmiot {
        
        private string nazwaField;
        
        private string prowadzacyField;
        
        private int ocenaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string nazwa {
            get {
                return this.nazwaField;
            }
            set {
                this.nazwaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string prowadzacy {
            get {
                return this.prowadzacyField;
            }
            set {
                this.prowadzacyField = value;
            }
        }
        
        /// <remarks/>
        public int Ocena {
            get {
                return this.ocenaField;
            }
            set {
                this.ocenaField = value;
            }
        }
    }		
}
